#!/bin/sh
LIST2KILL=""
LIST2WAIT=""
for cmd in "$@"; do {
  eval "$cmd" & pid=$!
  LIST2WAIT="$LIST2WAIT $pid"
  LIST2KILL="$LIST2KILL,$pid"
} done
LIST2KILL=`echo "$LIST2KILL" |cut -c 2-`

trap "pkill -P $LIST2KILL" INT TERM

wait $LIST2WAIT
