#!/bin/sh
set -e

mkdir -p "$HOME/.temp"
touch "$HOME/.temp/history"

if [ "$(../_os)" = "mac" ]; then
  is_mac="1"
else
  is_mac=""
fi

if [ "$is_mac" ]; then
  brew install bash-completion@2
  [[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]] && . "/opt/homebrew/etc/profile.d/bash_completion.sh"
fi

rc_file="$HOME"/."$(basename "$(which "$SHELL")")"rc
dir="$(dirname "$0")"
case "$(../_os)" in
  linux) echo "\n\n. \"$(realpath "$dir"/../rc/profile)\"" >> "$HOME/.profile" ;;
  mac)   echo "\n\n. \"$(realpath "$dir"/../rc/profile)\"" >> "$rc_file" ;;
esac
echo "\n\n. \"$(realpath "$dir"/../rc/rc)\"" >> "$rc_file"
# sudo sh -c "echo \"\\n. $(realpath ./rc/profile_root)\" >> /etc/environment"

read -p "GitHub name: " gh_name
read -p "GitHub email: " gh_email
git config --global user.name "${gh_name}"
git config --global user.email "${gh_email}"
# https://stackoverflow.com/questions/1899792/why-is-git-submodule-not-updated-automatically-on-git-checkout
git config --global submodule.recurse true

if [ "$is_mac" ]; then
  brew install gh
fi
gh auth login

printf '/.idea/\n/.venv/\n/__pycache__/\n' > "$HOME/.gitignore"
git config --global core.excludesFile "$HOME/.gitignore"
