#!/bin/sh
echo "\n\n. \"$(realpath ../rc/profile)\"" >> ~/.profile
echo "\n\n. \"$(realpath ../rc/rc)\"" >> ~/."$(basename $(which $SHELL))"rc
# sudo sh -c "echo \"\\n. $(realpath ./rc/profile_root)\" >> /etc/environment"
