#!/bin/bash
# $1 apt-list-installed.log
if [ ! "$1" ]; then
    echo "no apt-list-installed.log provided"
    exit 1
fi

log=$0.log
touch $log

# sed -r 's/^([^/]+)\/.*$/\1/' $1 |awk '{print $0; system("sudo apt-get install -y " $0 "; printf \"\\n\"")}' |tee -a $log

nr_lines=`cat $1 |wc -l`
echo $nr_lines
installed=$(apt list --installed)
ii=0
while read line; do
    echo "Progress: "$((ii * 100 *100 / nr_lines))"%%"
    ((++ii))
#    if [ $ii -eq 10 ]; then break; fi
    package=$(echo "$line" |sed -r 's/^([^/]+)\/.*$/\1/')
    reg="
$package/"
    if [[ "$installed" =~ "$reg" ]]; then
        # echo "Already installed"
        continue
    fi

    echo $package                    |tee -a $log
    sudo apt-get install -y $package |tee -a $log
    printf "\n\n"                    |tee -a $log
done <$1
