#!/bin/sh
operation="$1"
# dir=$(dirname $0)/backups
dir=$HOME/_/Programs/backups
dird="$dir/logs/$(date-filename)-$operation"
mkdir "$dird"
log="$dird/$operation.log"
touch "$log"

echo "$dird"
echo "$log"
