#!/bin/sh
flag="$1"
proc="$2"

echo "flag[$flag]"
echo "proc[$proc]"

if echo "$proc" | egrep -q '^[0-9]+$'; then
    pids="$proc"
else
    pids=$(proc $flag "$proc" |sed -r 's/^[^ ]+ +([0-9]+) .*$/\1/')
fi

if [ "$pids" ]; then
    echo "$pids" |while read pid; do
        if ps -p $pid > /dev/null; then
            if echo $pid |grep -E -v -x -q "($(_parents))"; then  # except this `fkill` and its parents
                children=$(pgrep -P $pid)
                if [ "$children" ]; then
                    echo "$children" |while read child; do
                        $0 "" $child
                    done
                fi
                if ps -p $pid > /dev/null; then
                    kill -9 $pid
                fi
            fi
        fi
    done
fi
