#!/bin/sh
# git add .
# # git add -u
# # git add -u -- .
# git commit -a -m "$@"

for command in \
    "git add $(_path 2 "$@")" \
    "git commit -m '$1'" \
; do
    echo "$command"
    eval "$command"
done
