#!/bin/sh
set -e
flags="$1"
files="$(_path 2 "$@")"

# git add .
# # git add -u
# # git add -u -- .
# git commit -a -m "$@"

git reset
eval "git add $files"

sign="(MacPaw|macpaw|MythicalGames)"
if [ "$sign" ]; then
    if git remote --verbose |grep -Eq "^origin( |\t)+git@github\.com:$sign/[^/ ]+ \(push\)$"; then
        flags="--gpg-sign $flags"
    fi
fi

eval "git commit $flags"  # `git commit -m "$1"` does not work
