#!/bin/sh
set -e

# git add .
# # git add -u
# # git add -u -- .
# git commit -a -m "$@"

flags="$1"
eval "git add $(_path 2 "$@")"

#if git remote --verbose |grep -Eq "^origin( |\t)+git@github\.com:(MacPaw|macpaw)/[^/ ]+ \(push\)$"; then
#    flags="--gpg-sign $flags"
#fi

eval "git commit $flags"  # `git commit -m "$1"` does not work
