#!/bin/sh
set -e

options="$1"
current_branch="$(_git-current-branch)"
command="git push --progress $options origin $current_branch"
linked=$(git remote show -n origin |grep -E "^ +$current_branch +merges with remote $current_branch$" && echo "1" || echo "")
if [ ! "$linked" ]; then
    command="$command --set-upstream"
fi
eval "$command"
