#!/bin/sh
# kill other instances of the script
procname=$(ps -o comm= $PPID)
# procname=$(realpath "$procname")
pgrep --exact "$procname" |egrep --invert-match --line-regexp "($(_parents))" |xargs --no-run-if-empty fkill
