#!/bin/sh

shells="$(_shells '\n')"
shells="$shells\n$(echo "$shells" |sed -r 's ^.*/([^/]+)$ \1 g')"
shells="$(echo "$shells" |tr '\n' '|' |sed -r 's/\|$//')"

nths_parent() {
    local n="$1"
    local parent="$(_parent)"
    while [ "$n" -gt 0 ]; do
        n=$((n - 1))
        parent="$(_parent "$parent")"
    done
    proc -x -P "$parent" |sed -r 's/^([^ ]+ +){10}(.+)$/\2/'
}

if nths_parent 2 |grep -E -q "^($shells|/bin/zsh --login -i)$"; then
    exit 1
fi

if nths_parent 3 |grep -E -q "^/Applications/Warp.app/Contents/MacOS/stable "; then
    exit 1
fi
