#!/bin/sh
set -e

os="$(uname -s)"
case "$os" in
    Darwin) echo "mac"                                  ;;
    Linux)  echo "linux"                                ;;
    *)      echo>&2 "$(realpath "$0"): unknown OS: $os" ;;
esac
