#!/bin/sh
if [ $# -ge 1 ]; then
    pid="$1"
else
    # pid=$PPID
    pid=$$
fi
if [ $# -ge 2 ]; then
    delim="$2"
else
    # delim="\n"
    delim="|"
fi

parent="$pid"
first="1"
while true; do
    parent=$(_parent $parent)

    if [ "$parent" = "0" ]; then
        alert "parent = 0"
        break
    fi
    if ! echo "$parent" | egrep -q '^[0-9]+$'; then
        alert "parent is not a nr: [$parent]"
        break
    fi

    if [ ! "$first" ]; then printf "$delim"; fi
    printf $parent
    first=""

    if [ "$parent" = "1" ]; then break; fi
done
