#!/bin/sh
if [ $# -ge 1 ]; then
    pid="$1"
else
    # pid=$PPID
    pid=$$  # --include actual caller (parent of this `_parent`)-- include this `_parent`
fi

if [ $# -ge 2 ]; then
    delim="$2"
else
    # delim="\n"
    delim="|"
fi

parent="$pid"
first="1"
while true; do
    parent=$(_parent $parent)

    if [ "$parent" = "0" ]; then
        alert "parent = 0; [$(procx $(_parent $pid))]"
        break
    fi
    if ! echo "$parent" | egrep -q '^[0-9]+$'; then
        alert "parent is not a nr: [$parent]; pid[$pid] _parent[$(_parent $pid)] procx-pid[$(procx $pid)] procx-parent[$(procx $(_parent $pid))]"
        break
    fi

    if [ ! "$first" ]; then printf "$delim"; fi
    printf $parent
    first=""

    if [ "$parent" = "1" ]; then break; fi
done
