#!/bin/sh

# echo "${@:2}"
# exit 0

if [ $# -gt $1 ]; then
    ii=0
    for arg in "$@"; do
        if [ $ii -ge $1 ]; then
            echo "$arg"
        fi
        ii=$(expr $ii + 1)
    done
else
    echo "."
fi
