#!/bin/sh

# echo "${@:2}"
# exit 0

if [ $# -ge 2 ]; then
    # echo "${@:2}"
    # echo "'${@:2}'"
    # echo "\"${@:2}\""

    ii=0
    for arg in "$@"; do
        if [ $ii -ne 0 ]; then
            echo "$arg"
        fi
        ii=$(expr $ii + 1)
    done
else
    echo "."
fi
