#!/bin/sh
set -e
if [ $# -ge 1 ]; then
    delim="$1"
else
    # delim="\n"
    delim="|"
fi

grep -E '^/' /etc/shells \
    |tr '\n' '|'         \
    |sed -r 's/\|$//'    \
    |tr '|' "$delim"     \
    &&:
