#!/bin/sh
set -e
window_name="$1"
timeout="$2"

[ "$(_os)" = "mac" ] || exit 1

now (){ date +"%s" ;}
start="$(now)"
reg='^ *pid = ([0-9]+) type="Foreground" .*$'
while :; do
    pid="$(lsappinfo list |grep -E --after-context=5 "^[0-9]+\) "'"'"$window_name"'"'"" |grep -E "$reg" |sed -r "s/$reg/\1/g")"
    if [ "$pid" ]; then
        break
    elif [ $(($(now) - start)) -gt "$timeout" ]; then
        exit 1
    else
        sleep 0.1
    fi
done
osascript -e '
    tell application "System Events"
        set targetPID to '"$pid"'
        repeat with proc in every process
            try
                if unix id of proc is targetPID then
                    set frontmost of proc to true
                    -- -- Try multiple activation methods
                    -- try
                    --     perform action "AXRaise" of window 1 of proc
                    -- end try
                    -- try
                    --     set position of proc to {0, 0}
                    -- end try
                    return "Activated PID: " & targetPID
                end if
            end try
        end repeat
        return "PID " & targetPID & " not found"
    end tell
'
