#!/bin/bash
windows () { wmctrl -p -l |grep -E ' AkelPad$' |sort ;}
prev_windows="$(windows)"
openwine ~/_/Programs/vendor/windows/AkelPad/AkelPad.exe "$1" ~/_/Programs/.wine2 &
for i in {1..5}; do
    new_windows="$(comm -1 -3 <(echo "$prev_windows") <(windows))"  # see `radio-nv.sh`
    if [ "$new_windows" ]; then
        # echo "$new_windows" |while read line; do
        # for line in ${new_windows//\\n/$cr}; do
        # new_windows="$(echo "$new_windows" |sed -r 's (^.*$) \"\1\" ')"; for line in $new_windows; do
        while read line; do
            proc_id="$(echo "$line" |sed -r 's/^([^ ]+ +){2}([0-9]+) .*$/\2/')"
            if echo "$$" |grep -Exq "($(_parents $proc_id))"; then
                window_id="$(echo "$line" |sed -r 's/^([^ ]+) .*$/\1/')"
                wmctrl -i -r "$window_id" -b remove,above
                exit 0
            fi
        # done
        done < <(echo "$new_windows")
    fi
    sleep 1
done

alert "$0: error"
exit 1
