#!/bin/sh
set -e
action="$1"

filename="$HOME/_/Programs/text@nezhraba/texts/aqi"
#notify (){ notify-send --urgency=low "aqi=$1" ;}
notify (){ echo "$1" > "$filename" ;}

good_level=30
bad_level=60
script=~/PycharmProjects/air-quality/main.py
options="Options: show full check"
#file=~/_/aqi.txt
#options="$options save saved"
case "$action" in
    show)  python "$script"        ;;
    full)  python "$script" --full ;;
    check)
        aqi=$($0 show |sed -r 's ^([0-9]+)(\..+)?$ \1 ')
        if [ $aqi -le $good_level ]; then
            notify "$aqi 🙂"
        elif [ $aqi -ge $bad_level ]; then
            notify "$aqi 🙁"
        else
            #rm "$filename"
            notify "$aqi"
        fi
        ;;
    #save)  $0 full >> "$file"      ;;
    #saved) tail -n1 "$file"        ;;
    help)  echo "$options"         ;;
    *)     echo>&2 "$options"      ;;
esac
