#!/bin/sh
set -e
action="$1"

good_level=30
script=~/PycharmProjects/air-quality/main.py
options="Options: show full check"
#file=~/_/aqi.txt
#options="$options save saved"
case "$action" in
    show)  python "$script"        ;;
    full)  python "$script" --full ;;
    check)
        aqi=$($0 show |sed -r 's ^([0-9]+)(\..+)?$ \1 ')
        if [ $aqi -le $good_level ]; then notify "aqi=$aqi"; fi
        ;;
    #save)  $0 full >> "$file"      ;;
    #saved) tail -n1 "$file"        ;;
    help)  echo "$options"         ;;
    *)     echo>&2 "$options"      ;;
esac
