#!/bin/sh
set -e
for i in 1 2 3 4 5; do
    if connected7 >/dev/null; then
        if [ "$(iwgetid -r)" = "TP-LINK_7DA0" ]; then
            exit 0
        else
            exit 1
        fi
    else
        sleep 1
    fi
done

exit 1
