#!/bin/bash
set -e

if wmctrl -l |grep Zoom > /dev/null; then
    exit 1
fi

for i in {1..10}; do  # bash
    if connected7 1 >/dev/null; then
        if [ "$(iwgetid -r)" = "TP-LINK_7DA0" ]; then
            exit 0
        else
            exit 1
        fi
    else
        sleep 1
    fi
done

exit 1
