#!/bin/bash
set -e
# if [ $(date +%s) -lt $(date +%s --date="2024-02-29 12:00") ]; then exit 1; fi
extra_checks="$1"
#home_routers=( "TP-LINK_7DA0" "Tenda_431D50" "Tenda_431D50_5G" "croft" )
home_routers=( "TP-LINK_7DA0" )

if [ "$extra_checks" ]; then
    # if wmctrl -l |grep Zoom > /dev/null; then
    #     exit 1
    # fi

    if [ "$(mic-status)" = "on" ]; then
        exit 1
    fi

    # # if anything is in fullscreen
    # cur_workspace="$(wmctrl -d |grep -E '^[0-9]+ +\*')"
    # cur_workspace_id="$(echo "$cur_workspace" |sed -r 's/^([0-9]+) .*$/\1/')"
    # cur_workspace_dim="$(echo "$cur_workspace" |sed -r 's/^[0-9]+ +[-*]+ DG: ([0-9]+)x([0-9]+) .*$/\1 \2/')"
    # if wmctrl -l -G |grep -E "^[^ ]+ +$cur_workspace_id +[0-9]+ +[0-9]+ +$cur_workspace_dim " > /dev/null; then
    #     exit 1
    # fi

    if _external-display-connected; then
        exit 1
    fi
fi

for i in {1..10}; do  # bash
    connected_router="$(iwgetid -r ||:)"
    #if [[ "${IFS}${home_routers[*]}${IFS}" =~ "${IFS}${connected_router}${IFS}" ]]; then
    #    exit 0
    #else
    #    exit 1
    #fi
    for home_router in ${home_routers[@]}; do
        if [ "$connected_router" = "$home_router" ]; then exit 0; fi
    done
    sleep 1
done

exit 1
