#!/bin/bash
set -e
action="$1"

dir="$HOME/.temp/brightness"

nr_args=$#
eval last=\${$#}
options() {
    if [ "$last" = "help" ]; then
        local nr=$((nr_args - 1))
        eval option=\${$nr}
        echo "Options: $option"
        exit
    fi
}

case "$action" in
    set)
        channel="$2"
        value="$3"

        options "user" "100"

        $0 transition "$channel"  # kill a running one

        current() { [ -f "$dir/$channel" ] && cat "$dir/$channel" || echo 100 ;}
        case "${value:0:1}" in  # bash
            +) value=$(($(current) + ${value:1})) ;;  # bash
            -) value=$(($(current) - ${value:1})) ;;  # bash
        esac
        printf "$value" > "$dir/$channel"
        ;;
    get|"")
        final="$(echo "scale=2; $(brightnessctl get) * 100 / $(brightnessctl max)" |bc |sed -r 's/\.00$//')"
        if [ $(nr-files "$dir") -eq 0 ]; then
            echo "$final"
        else
            for channel in $(ls -1 "$dir"); do
                echo "$channel: $(cat "$dir/$channel")"
            done
            echo ""
            echo "final: $final"
        fi
        ;;
    update)
        final="$(brightnessctl max)"
        min=$((final * 5 / 1000 + 1))
        for channel in $(ls -1 "$dir"); do
            value="$(cat "$dir/$channel")"
            if echo "$value" |grep -Eq "^[1-9][0-9]{0,2}$"; then
                final=$((final * value / 100))
                [ "$value" -ne 100 ] || rm "$dir/$channel"
            else
                echo "channel[$channel] value[$value]" >&2
                rm "$dir/$channel"
            fi
        done
        [ $final -ge $min ] || final=$min
        sudo brightnessctl set $final
        ;;
    daemon)
        _highlander 1
        $0 set user 100
        $0 update
        inotifywait --monitor --quiet --event CLOSE_WRITE -- "$dir" |while read; do
            $0 update
        done
        ;;
    transition)
        _highlander 2
        channel="$2"

        options "user" "100" "$(date +%R)" "1" "$(date --date="+1 hour" +%R)"

        if [ "$6" ]; then
            dir="$HOME/PycharmProjects/light"
            "$dir/venv/3.11/bin/python" "$dir/screen-brightness.py" "$channel" "$3" "$4" "$5" "$6"
        fi
        ;;
    help) echo "Options: set get transition" ;;
    *) echo "set get update daemon transition" >&2 ;;
esac
