#!/bin/bash
set -e
action="$1"

#channels="user scene power"
#pipe="$HOME/.temp/brightness"
dir="$HOME/.temp/brightness"

#if [[ " $channels " =~ " $action " ]]; then  # bash
#    echo "$action $2" > "$pipe"
#    exit 0
#fi
case "$action" in
    set)
        channel="$2"
        value="$3"

        if [ "$channel" = "help" ]; then
            echo "Options: user"
            exit
        fi
        if [ "$value" = "help" ]; then
            echo "Options: 100"
            exit
        fi

        $0 transition "$channel"  # kill a running one

        current() { [ -f "$dir/$channel" ] && cat "$dir/$channel" || echo 100 ;}
        case "${value:0:1}" in  # bash
            +) value=$(($(current) + ${value:1})) ;;  # bash
            -) value=$(($(current) - ${value:1})) ;;  # bash
        esac
        printf "$value" > "$dir/$channel"
        ;;
    get|"")
        final=$(($(brightnessctl get) * 100 / $(brightnessctl max)))
        if [ $(nr-files "$dir") -eq 0 ]; then
            echo "$final"
        else
            for channel in $(ls -1 "$dir"); do
                echo "$channel: $(cat "$dir/$channel")"
            done
            echo ""
            echo "final: $final"
        fi
        ;;
    update)
        final=100
        for channel in $(ls -1 "$dir"); do
            value="$(cat "$dir/$channel")"
            if echo "$value" |grep -Eq "^[1-9][0-9]{0,2}$"; then
                final=$((final * value / 100))
                [ "$value" -ne 100 ] || rm "$dir/$channel"
            else
                echo "channel[$channel] value[$value]" >&2
                rm "$dir/$channel"
            fi
        done
        [ "$final" -ge 1 ] || final=1
        sudo brightnessctl set "$final"%
        ;;
    daemon)
        _highlander 1
        #for channel in $channels; do
        #    eval "$channel=100"
        #done
        #[ -p "$pipe" ] || mkfifo "$pipe"
        #function apply {
        #    local final=100
        #    for channel in $channels; do
        #        local value="${!channel}"  # bash
        #        final=$((final * value / 100))
        #    done
        #    [ "$final" -ge 1 ] || final=1
        #    sudo brightnessctl set "$final"%
        #}
        #apply
        #tail -f "$pipe" |while read channel value; do
        #    if echo "$value" |grep -Eq "^[1-9][0-9]{0,2}$"; then
        #        eval "$channel=$value"
        #        apply
        #    else
        #        echo "channel[$channel] value[$value]" >&2
        #    fi
        #done
        $0 set user 100
        $0 update
        inotifywait --monitor --quiet --event CLOSE_WRITE -- "$dir" |while read; do
            $0 update
        done
        ;;
    transition)
        _highlander 2
        channel="$2"

        if [ "$6" ]; then
            dir="$HOME/PycharmProjects/light"
            "$dir/venv/3.11/bin/python" "$dir/screen-brightness.py" "$channel" "$3" "$4" "$5" "$6"
        fi
        ;;
    #"") echo "get" > "$pipe" ;;
    #help) echo "Options: $channels" ;;
    #*) echo "$channels daemon" >&2 ;;
    help) echo "Options: set get update" ;;
    *) echo "set get update daemon transition" >&2 ;;
esac
