#!/bin/sh
url=127.0.0.1
port=8703

reg='^\[[^]]+\]  "[^G]*GET[^/]+/([^"]+)".*$'
# reg='^\[[^]]+\]  "[^G]*GET[^/]+/([[:print:]]+)[^[[:print:]]].*$'
# grep + sed don't work..
http-server  -a $url -p $port 2>/dev/null |while read line; do
    if [ "$(echo "$line" |grep -E "$reg")" ]; then
        title="$(echo "$line" |sed -r "s~$reg~\1~")"
        length=$(echo "$title" |awk '{print length($0)}')
        title="$(echo "$title" |cut -c1-$(($length-5)))"
        title="$(echo "$title" |php -r 'echo urldecode(fgets(STDIN));')"
        alert "closing browser tab [$title]"
        xdotool search --name "^$title - Vivaldi$" windowactivate --sync %1 key ctrl+w windowactivate $(xdotool getactivewindow)
    fi
done
