#!/bin/sh
parallel "
    /usr/bin/conky -c ~/_/Programs/vendor/conky/Conky_Arc_Light/.conkyrc
    /usr/bin/conky -c ~/_/Programs/vendor/conky/greenish/config/greenish
    # /usr/bin/conky -c ~/_/Programs/vendor/conky/InfinitySVG/.conkyrc
    # /usr/bin/conky -c ~/_/Programs/vendor/conky/conkyrc_seamod/conkyrc_seamod
"

# /usr/bin/conky -c ~/_/Programs/vendor/conky/lsd-conky/.conkyrc
