#!/bin/sh
# /usr/bin/conky -c ~/.conky/Conky_Arc_Light/.conkyrc
parallel \
    "/usr/bin/conky -c ~/.conky/Conky_Arc_Light/.conkyrc" \
    "/usr/bin/conky -c ~/.conky/greenish/config/greenish"
# /usr/bin/conky -c conkyrc_seamod/conkyrc_seamod
