#!/bin/bash
timeout="$1"
if [ ! "$timeout" ]; then timeout=3; fi

if timeout "$timeout"s ping -c 1 -n google.com > /dev/null; then
    echo "Connected"
    exit 0
else
    echo "Disconnected" >&2
    exit 1
fi
