#!/bin/sh

# self-control
codename="_$(basename $0)"
run-detached -q "
    while :; do
        if ! procx $$ > /dev/null; then
            alert '$codename failed'
            break
        fi
        sleep 10
    done
"

first="1"  # for starting processes

while true; do
    for cmd in "$@"; do
        if [ ! "$(procx "$cmd")" ]; then
            if [ "$first" ]; then
                first=""
            else
                alert "process down; restarting: $cmd"
            fi
            run-detached "$cmd"
        fi
    done
    sleep 10
done
