#!/bin/sh
_highlander
while true; do
    for cmd in "$@"; do
        if [ ! "$(procx "$cmd")" ]; then
            alert "process down; restarting: $cmd"
            run-detached "$cmd"
        fi
    done
    sleep 10
done
