#!/bin/sh
_highlander
while true; do
    for cmd in "$@"; do
        if [ ! "$(procx "$cmd")" ]; then
            alert "process down; restarting: $cmd"
            # eval "$cmd" &
            # $("$cmd") &
            sh -c "$cmd" & # run in detached mode - no connection with this parent `daemons`
        fi
    done
    sleep 10
done
