#!/bin/sh
set -e

case "$(_os)" in
    linux)
        # df -h --output=source,target,fstype
        df -h --type=ext4 --type=fuseblk --output=target,size,used,avail,pcent
        ;;
    mac)
        df -h -I
        ;;
esac
