#!/bin/sh
set -e

minutes="$1"
sendkey () { xdotool key Super_L+i ;}
sendkey

# sleep "$minutes"m
seconds=$((minutes * 60))
while [ $seconds -gt 0 ]; do
    printf "\r%2d:%02d" $((seconds / 60)) $((seconds - seconds / 60 * 60))
    seconds=$((seconds - 1))
    sleep 1
done

sendkey
