#!/bin/sh
set -e
minutes="$1"

sendkey() { xdotool key Super_L+i ;}
sendkey

deadline=$(date --date="+$minutes minutes" +%s)
while :; do
    seconds_left="$(echo "$deadline - $(date +%s)" |bc)"
    [ $(echo "$seconds_left > 0" |bc) -eq 1 ] || break
    printf "\r%2d:%02d" $((seconds_left / 60)) $((seconds_left % 60))
    sleep 1
done

sendkey
