#!/bin/sh
docker system prune --all --force --volumes
exit 0

# docker rm --force $(docker container ls -a -q)
# docker rmi --force $(docker images -a -q)

docker container ls -a -q |xargs -r -- docker rm  --force
docker images -a -q       |xargs -r -- docker rmi --force
