#!/bin/sh
set -e
dir=/tmp/errors

process() {
    file="$1"

    content="$(cat "$dir/$file")"
    if [ "$content" ]; then
        alert "$file: $content"
        echo -n > "$dir/$file"
    fi
}

case "$1" in
    for)
        name="$2"
        reg='^([^ ]*/)?([0-9a-zA-Z._-]{1,30})( .*)?$'
        if echo "$name" |grep -Eq "$reg"; then
            name="$(echo "$name" |sed -r "s#$reg#\2#")"
        else
            name="$PPID"
        fi
        echo "$dir/$name"
        ;;
    #for2)
    #    name="$2"
    #    if ! echo "$name" |grep -Ei '^[0-9a-z .-]{1,30}$' > /dev/null; then
    #        name="$PPID"
    #    fi
    #    pipe="/tmp/errors2/$name"
    #    mkfifo "$pipe"
    #    run-detached "$0 listen2 ${pipe}" >/dev/null
    #    echo "$pipe"
    #    ;;
    init)
        mkdir -p "$dir"
        if [ $(nr-files "$dir") -gt 0 ]; then rm -f "$dir"/*; fi
        ;;
    listen)
        _highlander
        ls -1A "$dir" |while read file; do
            process "$file"
        done
        inotifywait --monitor --quiet --format "%f" --event MODIFY -- "$dir" |while read file; do
            if [ -f "$dir/$file" ]; then
                process "$file"
            fi
        done
        ;;
    #listen2)
    #    tail --follow=name "$2" |while read line; do
    #        alert "$2: $line"
    #    done
    #    ;;
    help) echo "Options: for init listen" ;;
    *) echo "unknown option: $1" >"$($0 for $0)"; exit 1 ;;
esac
