#!/bin/sh
set -e

_cmd "findp $(_path 2 "$@") -regextype awk -iregex '.*($1)[^/]*' -exec ls -dp {} \;" \
    |sort --version-sort                                                             \
    |grep -iE --color=auto "$1"                                                      \
&&:
