#!/bin/sh
findcommand='find . -not -path . -type f'
nrfiles=$(eval "$findcommand"| wc -l)
ii=0
eval "$findcommand" |while read fname; do
  ii=$(expr $ii + 1)
  printf "\t"; echo "$ii/$nrfiles $fname"
  if [ $(mimetype -b - "$fname"| grep 'image') ]; then
    identify "$fname" > /dev/null 2> /dev/null || echo "$fname"
  else
    : #printf "\tnot an image\n"
  fi
done
