#!/bin/sh
# grep -Hrina --color=auto --exclude-dir=.git "$1" $(_path "$@")
grep --with-filename --recursive --ignore-case --line-number --binary-files=text --color=auto --exclude-dir=.git -- "$1" $(_path "$@")
