#!/bin/sh
set -e

case "$(_os)" in
    linux) regex_args="-regextype awk -iregex '.*($1)[^/]*'" ;;
    mac)   regex_args="-iregex '.*$1[^/]*'"                  ;;
esac

eval "findp $(_path 2 "$@") $regex_args -exec ls -dp {} \;" \
    |sort --version-sort                                                             \
    |grep -iE --color=auto "$1"
