#!/bin/sh
if echo "$1" | egrep -q '^[0-9]+$'; then
    pids="$1"
else
    # pids=$(proc "$1" |grep -v "$0" |sed -r 's/^[^ ]+ +([0-9]+) .*$/\1/')
    pids=$(proc "$1" |sed -r 's/^[^ ]+ +([0-9]+) .*$/\1/')
fi

if [ "$pids" ]; then
    echo "$pids" |while read pid; do
        if ps -p $pid > /dev/null; then
            if ! [ "$(ps -p $pid |grep $(basename $0))" ]; then
                children=$(pgrep -P $pid)
                if [ "$children" ]; then
                    echo "$children" |while read child; do
                        $0 $child
                    done
                fi
                if ps -p $pid > /dev/null; then
                    # kill -9 $pid
                    # echo "kill -9 $pid"
                    kill -9 "$pid"
                fi
            fi
        fi
    done
fi
