#!/bin/sh
set -e

#src="$1"
#dest="$2"

src=${1%/}
name=${src##*[/:]}
dest=${2:-${name%.git}}

#git clone https://github.com/$src "$dest"
#git clone --recurse-submodules "git@github.com:$src" "$dest"
git clone --recurse-submodules                                                                 \
    "$(printf %s "$src" | sed -E '/:/! { \,/.*/,! s|^|github.com/|; s|^([^/]+)/|git@\1:|; }')" \
    "$dest"                                                                                    \
&&:

# initialize .git/FETCH_HEAD, used by `gst`
git -C "$dest" fetch
