#!/bin/sh
set -e

destination="$2"
if [ ! "$destination" ]; then
    destination="$(echo "$1" |sed -r "s ^.*/([^/]+)$ \1 ")"
fi

# git clone https://github.com/$1/$2 $3
git clone "git@github.com:$1" "$destination"

# initialize .git/FETCH_HEAD, used by `gst`
git -C "$destination" fetch
