#!/bin/bash
set -e
message="$1"

_ignore-completion "$message"

#message="$(echo "$message" |sed -r 's/'"'"'/'"'"'"'"'"'"'"'"'/g')"
a="'"
message="$(echo "$message" |sed -r "s/$a/$a\"$a\"$a/g")"
_gcm "--message='$message'" "${@:2}"
printf "\n"

if ! _is_in_script; then
    gst
fi
