#!/bin/bash
set -eu
message="$1"

_ignore-completion "$message"

#message="$(echo "$message" |sed -r 's/'"'"'/'"'"'"'"'"'"'"'"'/g')"
a="'"
message="$(echo "$message" |sed -r "s/$a/$a\"$a\"$a/g")"
[ "$message" != "." ] && edit="--edit" || edit=""
_gcm "--message='$message' $edit" "${@:2}"
printf "\n"

_is_in_script || gst
