#!/bin/sh
set -e
branch="$1"
key="$(basename $0)"

if ! gst > /dev/null; then
    #_git-real add .
    _git-real stash push --include-untracked --message "$key"
fi

_git-real checkout "$branch"

branch="$(echo $branch |sed -r 's / \\/ g')"
echo "$(_git-real --no-pager stash list)" |while read stash; do
    match="$(echo "$stash" |sed -r "s/^stash@\{([0-9]+)\}: On $branch: $key$/\1/")"
    if [ "$(echo $match |grep -E '^[0-9]+$')" ]; then
        _git-real stash pop "stash@{$match}"
        break
    fi
done
