#!/bin/sh
set -e

if [ "$1" = "" ]; then
    git clean -n
    git clean -f
    git checkout -- .
    git add .
    #git rm --cached -r -f .
    git reset --hard
else
    eval "git checkout HEAD -- $(_path 1 "$@")"
fi
