#!/bin/sh
set -e
branch="$1"

git merge "$branch"
git branch --delete "$branch"

if git ls-remote --exit-code --heads origin "$branch" > /dev/null; then
    git branch --delete --remotes origin/"$branch" ||:
fi
