#!/bin/sh
set -e

has_changes=$(gst > /dev/null && echo "1" || echo "")
if [ "$has_changes" ]; then gsh-save; fi
git pull
if [ "$has_changes" ]; then gsh-pop; fi

# # git config --global pull.ff only
# git fetch --all
# git status -sb
# git rebase my_feature upstream/master

# !git fetch origin --tags --prune
# !git merge @{u} --ff-only && git l1
