#!/bin/sh
# linked=$(git remote show origin |grep "HEAD branch: master" && exit 0 || exit 1)
linked=$(git remote show -n origin |grep "master" && exit 0 || exit 1)
if [ "$linked" ]; then
    git push
else
    git push --set-upstream origin master
fi
