#!/bin/sh
set -e

if [ "$1" = "dir" ]; then
    find "$HOME/_/Programs/vendor/JetBrains/Toolbox/apps/$2" \
        -mindepth 2                                          \
        -maxdepth 2                                          \
        -type d                                              \
        -not -name '*plugins'                                \
        |sed -r 's ^.*/([^/]+)$ \1:\0 '                      \
        |sort -rV                                            \
        |head --lines=1                                      \
        |sed -r 's ^.+:(.+)$ \1 '
else
    sh $1
    #sleep 5m
fi
