#!/bin/sh
set -e
version2="$1"
[ "$version2" != "" ] || version2=3

python="python$version2"
reg="^Python ([0-9]+(\\.[0-9]+){2})$"
version3="$($python --version)"
if echo "$version3" |grep -Eq "$reg"; then
    version3="$(echo "$version3" |sed -r "s/$reg/\1/")"
else
    echo>&2 "Invalid version: $version3"
    exit 1
fi

mkdir -p .venv
$python -m venv ".venv/$version3"
"./.venv/$version3/bin/pip" install --upgrade pip setuptools wheel

requirements="requirements.txt"
if [ -f "$requirements" ]; then
    "./.venv/$version3/bin/pip" install -r "$requirements"
fi
