#!/bin/bash
set -e

# helpers
strip_head() {
    local text="$1"

    local nr_lines="$(echo "$text" |wc -l)"
    echo "$text" |tail --lines="$((nr_lines - 1))"
}
indented() {
    local indent="$1"
    local value="$2"

    echo "$value" |sed -r "s/^/$indent/"
}
nth() {
    local text="$1"
    local column="$2"

    local groups=" *"
    if [ "$column" -gt 1 ]; then
        for _ in $(seq 1 "$((column - 1))"); do
            groups="$groups""[^ ]+ +"
        done
    fi
    echo "$text" |sed -r "s/^$groups([^ ]+) +.*$/\1/"
}
no() {
    case "$1" in
        "")   return 0 ;;
        help) return 0 ;;
        *)    return 1 ;;
    esac
}
keep() {
    local text="$1"

    [ "$text" ] && text="$text. "
    printf "%sPress [enter] to stop" "$text"
    read -r
}

# autocomplete & arguments
args=$*
current_arg_file=/tmp/current-arg
echo 0 > "$current_arg_file"
next_arg() {
    current_arg="$(cat "$current_arg_file")"
    echo "$((current_arg + 1))" > "$current_arg_file"
    reg="^([^ ]+ +){$current_arg}([^ ]+).*$"
    if echo "$args" |grep -Eq "$reg"; then
        echo "$args" |sed -r "s/$reg/\2/"
    fi
}
options() {
    echo "Options: $*"
    exit 0
}
no_more_args() {
    echo>&2 "No more arguments available"
}

# company-specific
filter_pods() {
    local pods="$1"

    echo "$pods" |sed -r 's/^linkerd-proxy,//g'
}
service_port() {
    local namespace="$1"
    local container="$2"

    # kubectl get svc --namespace="$namespace" |grep -E "^$container "
    reg="^Port: +[a-z]+ +([0-9]+)/[A-Z]+$"
    kubectl describe service --namespace="$namespace" "$container" \
        |grep -E "$reg"                                            \
        |grep --invert-match metrics                               \
        |sed -r "s#$reg#\1#g"                                      \
    &&:
}

# list resources
projects() {
    local projects="$(gcloud projects list)"
    nth "$(strip_head "$projects")" 1
}
clusters() {
    local project="$1"

    local clusters="$(gcloud container clusters --project="$project" list  2>/dev/null)"
    strip_head "$clusters" |sed -r 's/^([^ ]+) +([^ ]+) .*$/\1:\2/g'
}
authenticate() {
    local project="$1"
    local cluster="$2"

    reg='^([^:]+):([^:]+)$'
    local cluster_name="$(echo "$cluster" |sed -r "s/$reg/\1/")"
    local cluster_location="$(echo "$cluster" |sed -r "s/$reg/\2/")"

    gcloud container clusters --project "$project" get-credentials "$cluster_name" --zone "$cluster_location"  2>/dev/null
}
contexts() {
    nth "$(strip_head "$(kubectl config get-contexts)")" 1
}
namespaces() {
    local namespaces="$(kubectl get namespace)"
    nth "$(strip_head "$namespaces")" 1
}
containers() {
    local namespace="$1"

    local containers="$(kubectl get pods --namespace="$namespace" -o custom-columns="CONTAINER:.spec.containers[*].name")"
    filter_pods "$(strip_head "$containers")" |sort |uniq
}
list_pods_for_namespace() {
    local namespace="$1"

    kubectl get pods --namespace="$namespace"
}
pods_for_namespace_container() {
    local namespace="$1"
    local container="$2"

    local containers_pods="$(                                                         \
        kubectl get pods                                                              \
            --namespace="$namespace"                                                  \
            -o custom-columns="CONTAINER:.spec.containers[*].name,POD:.metadata.name" \
        &&:
    )"
    filter_pods "$(strip_head "$containers_pods")" |grep -E "^$container " |sed -r "s/^.+ +(.+)$/\1/g"
}
hosts() {
    kubectl get ingress --all-namespaces
}

# commands (operations)
current_context() {
#    kubectl config view --minify -o jsonpath='{..current-context}'
    kubectl config current-context
}
set_context() {
    local context="$1"

    kubectl config use-context "$context" >/dev/null
}
dump_hosts() {
    contexts |while read -r context; do
        echo "$context"
        set_context "$context"
        indented "  " "$(hosts)"
    done
    close >/dev/null
}
telepresence_() {
    telepresence connect
    keep "Telepresence started."
    telepresence quit --stop-daemons
}
port_forward() {
    local namespace="$1"
    local container="$2"

    local pod="$(pods_for_namespace_container "$namespace" "$container" |head --lines=1)"
    local port="$(service_port "$namespace" "$container")"

    kubectl port-forward --namespace="$namespace" "$pod" "$port" || alert "port-forward connection lost"
}
logs() {
    local namespace="$1"

    printf "search: "
    read -r search
    [ "$search" ] || search=".*"
    stern --namespace "$namespace" "$search" ||:
}
close() {
    #kubectl config delete-context "$(current_context)"
    #kubectl config unset clusters
    kubectl config unset current-context

    rm -f "$current_arg_file"
}

command_hosts="-hosts"
command_current_context="-current-context"
command_authenticate="-authenticate"
command_close="-close"
command_keep="-keep"
command_telepresence="-telepresence"
command_statuses="-statuses"
command_logs="-logs"
command_port_forward="-port-forward"

#gcloud auth login
#kubectl api-resources  # list resource types
#kubectx  # list or select context (project+cluster)
:

#<editor-fold desc="context">
context="$(next_arg)"
if no "$context"; then
    options "--command: $command_hosts $command_current_context $command_authenticate $command_close .context: $(contexts)"
fi
case "$context" in
    "$command_hosts")           dump_hosts      ;;
    "$command_current_context") current_context ;;
    "$command_close")           close           ;;
    "$command_authenticate")
        project="$(next_arg)"
        if no "$project"; then
            options ".project: $(projects)"
        fi

        cluster="$(next_arg)"
        if no "$cluster"; then
            options ".cluster: $(clusters "$project")"
        fi

        if [ "$(current_context 2>/dev/null)" != "gke_$project""_$(echo "$cluster"| sed -r 's/^(.+):(.+)$/\2_\1/')" ]; then
            authenticate "$project" "$cluster"
            echo>&2 "authenticated to project[$project]cluster[$cluster]"
        fi
        ;;
    *) continue="1" ;;
esac
if [ "$continue" ]; then
    continue=""
else
    close
    exit 0
fi

set_context "$context"
echo>&2 "using context [$context]"
#</editor-fold>

#<editor-fold desc="namespace">
# kubens
# kubectl config view --minify -o jsonpath='{..namespace}'
namespace="$(next_arg)"
if no "$namespace"; then
    options "--command: $command_telepresence $command_keep $command_hosts .namespace: $(namespaces)"
fi
case "$namespace" in
    "$command_telepresence") telepresence_ ;;
    "$command_keep")         keep          ;;
    "$command_hosts")        hosts         ;;
    *)                       continue="1"  ;;
esac
if [ "$continue" ]; then
    continue=""
else
    close
    exit 0
fi
#</editor-fold>

#<editor-fold desc="container">
container="$(next_arg)"
if no "$container"; then
    options "--command: $command_statuses $command_logs .container: $(containers "$namespace")"
fi
case "$container" in
    "$command_statuses") list_pods_for_namespace "$namespace" ;;
    "$command_logs")     logs "$namespace"                    ;;
    *)                   continue="1"                         ;;
esac
if [ "$continue" ]; then
    continue=""
else
    close
    exit 0
fi
#</editor-fold>

#<editor-fold desc="command">
command="$(next_arg)"
if no "$command"; then
    options "--command: $command_port_forward"
fi
case "$command" in
    "$command_port_forward") port_forward "$namespace" "$container" ;;
    *)                       continue="1"                           ;;
esac
if [ "$continue" ]; then
    continue=""
else
    close
    exit 0
fi
#</editor-fold>

close

# [other]
#kubectl get nodes
#procs="$(kubectl exec "$pod" --container "$container" -- )"

#columns="NAMESPACE:.metadata.namespace,CONTAINER:.spec.containers[*].name,NODE:.spec.nodeName,POD:.metadata.name"
#script=$(cat <<PYTHON
#    import sys
#    lines = sys.stdin.read().split("\n")
#    keys, headers = lines.pop(0).split("|")
#    def split(line: str) -> list[str]:
#        return list(filter(None, line.split(" ")))
#    keys = split(keys)
#    headers = split(headers)
#    d = {}
#    for line in lines:
#        d2 = d
#        for w in split(line):
#            if w not in d2:
#                d2[w] = {}
#            d2 = d2[w]
#    #def p(v: dict, indent: str) -> None:
#    #    for k in v.keys():
#    #        print(indent + k)
#    #        p(v[k], indent + "  ")
#    #p(d, "    ")
#    for key in keys:
#        if key in d:
#            d = d[key]
#            headers = headers[1:]
#        else:
#            break
#    print(f"_{headers[0].lower()}: " + " ".join(list(d.keys())))
#PYTHON
#)
#script=$(                                    \
#    echo "$script"                           \
#        |sed -r "s/^$(                       \
#            echo "$script"                   \
#                |head --lines=1              \
#                |sed -r "s/^( *)[^ ].*$/\1/" \
#        )//g"                                \
#)
#table="$(kubectl get pods --all-namespaces -o custom-columns="$columns")"
#options "$(echo "$(next_arg) $(next_arg) $(next_arg) $(next_arg)|$table" |python3 -c "$script")"

#echo "project[$project] cluster_name[$cluster_name] cluster_location[$cluster_location] namespace[$namespace]"
