#!/bin/sh
late="21:15"
early="05:00"

current=""
prev=""
while true; do
    now=$(date +%s)
    if [ $now -ge $(date -d $late +%s) ] || [ $now -le $(date -d $early +%s) ]; then
        current="0.5"
        daytime="night"
        prev_dt="day"
    else
        current="1.0"
        daytime="day"
        prev_dt="night"
    fi

    if [ "$current" != "$prev" ]; then
        brightness "$current"

        filename="$HOME/.temp/backgrounds.txt"
        touch "$filename"

        # save cur bg
        if [ "$prev" != "" ]; then
            sed -i "/^$prev_dt:.*\$/d" "$filename"
            echo "$prev_dt: $(get-background)" >> "$filename"
        fi

        # set new bg
        bg="$(cat "$filename" |grep -E "^$daytime:" |sed -r "s/^$daytime: (.*)$/\1/")"
        if [ "$bg" ]; then
            set-background "$bg"
        fi

        prev="$current"
    fi

    sleep 1
done
