#!/bin/sh
day="05:00"
evening="19:30"
night="21:15"
# daytime_file="$(echo "~/MEGAsync/browser extensions/darkreader/index.html" |sed -r 's| |\\ |g')"
daytime_file="$(realpath ~/MEGAsync/browser\ extensions/darkreader/index.html)"

day="$(date -d $day +%s)"
evening="$(date -d $evening +%s)"
night="$(date -d $night +%s)"

case "$1" in
    day|evening|night) echo "$1" > "$daytime_file" ;;
    update)
        prev=""
        while true; do
            now=$(date +%s)
            if [ $now -ge $day ] && [ $now -lt $evening ]; then
                daytime="day"
            else
                if [ $now -lt $night ]; then
                    daytime="evening"
                else
                    daytime="night"
                fi
            fi

            if [ "$daytime" != "$prev" ]; then
                prev="$daytime"
                echo "$daytime" > "$daytime_file"
            fi

            sleep 1
        done
        ;;
    server)
        # http-server ~/MEGAsync/browser\ extensions/darkreader/ -a 127.0.0.1 -p 9473
        # http-server "$(dirname "$daytime_file")/" -a 127.0.0.1 -p 9473
        eval "http-server $(dirname "$daytime_file" |sed -r 's| |\\ |g') -a 127.0.0.1 -p 9473"
        # http-server "$(dirname "$daytime_file" |sed -r 's| |\\ |g')" -a 127.0.0.1 -p 9473
        ;;
    main)
        prev=""
        while true; do
            daytime=$(cat "$daytime_file")
            if [ "$daytime" != "$prev" ]; then
                case "$daytime" in
                    day)
                        brightness 1.0
                        prev_dt="night"
                        ;;
                    evening)
                        brightness 0.5
                        prev_dt="day"
                        ;;
                    night)
                        brightness 0.25
                        prev_dt="evening"
                        ;;
                esac

                bgs_file="$HOME/.temp/backgrounds.txt"
                touch "$bgs_file"
                # save cur bg
                if [ "$prev" != "" ]; then
                    sed -i "/^$prev_dt:.*\$/d" "$bgs_file"
                    echo "$prev_dt: $(get-background)" >> "$bgs_file"
                fi
                # set bg for current time-of-day
                bg="$(cat "$bgs_file" |grep -E "^$daytime:" |sed -r "s/^$daytime: (.*)$/\1/")"
                if [ "$bg" ]; then
                    set-background "$bg"
                fi

                prev="$daytime"
            fi
            sleep 1
        done
        ;;
    all)
        parallel -n "
            $0 update
            $0 server
            $0 main
        "
        ;;
    *)
        # echo "Options: day night update server main"
        echo "Options: day evening night"
        ;;
esac
