#!/bin/sh
set -e

last_arg=""
for input; do last_arg="$input"; done

case "$last_arg" in
    help|info|brightness) ;;
    *) _highlander ;;
esac

dir="$HOME/PycharmProjects/light"
"$dir/venv/3.11/bin/python" "$dir/main.py" "$@"
