#!/bin/sh
set -e

opts="Options: latitude longitude help"
case "$1" in
    latitude)  printf 49.087    ;;
    longitude) printf 26.259    ;;
    help)      echo "$opts"     ;;
    *)         echo "$opts" >&2 ;;
esac
