#!/bin/sh
set -e

opts="Options: latitude longitude help"
case "$1" in
    latitude)  printf 50.425    ;;
    longitude) printf 30.518    ;;
    #latitude)  printf 49.405    ;;  # хмель
    #longitude) printf 26.99     ;;
    help)      echo "$opts"     ;;
    *)         echo "$opts" >&2 ;;
esac
