#!/bin/sh
set -e

line="$(tail -1 "$HOME/.temp/ac-power.log")"
logged(){
    local reg="(^.+): ([^:]+)$"
    echo "$line" |sed -r "s/$reg/\\$1/"
}
logged_time="$(logged 1)"
if [ "$(logged 2)" = "on" ]; then
    logged_state=1
else
    logged_state=0
fi
if [ "$(_battery-data 1 online)" = "yes" ]; then
    online=1
else
    online=0
fi

if [ $online -eq $logged_state ]; then
    if [ $(( $(date -d "$logged_time" +%s) + 1 )) -ge $(date +%s) ]; then
        exit 1
    fi
fi

receiver="$(dbus-send --print-reply --dest=org.freedesktop.DBus  /org/freedesktop/DBus org.freedesktop.DBus.ListNames |grep org.mpris.MediaPlayer2 |tail -1)"
if [ "$receiver" ]; then
    receiver="$(echo "$receiver" |sed -r 's/^ *string "(.+)"$/\1/')"
    dbus-send --print-reply --dest="$receiver" /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause
else
    xdotool key XF86AudioPlay
fi

# xdotool key --clearmodifiers XF86AudioPlay

# xdotool keyup KP_Space
# xdotool keyup Super_L
# xdotool key XF86AudioPlay

# xdotool key --clearmodifiers XF86AudioPlay
# sleep 0.1
# xdotool keyup KP_Space
# xdotool keyup Super_L
