#!/bin/sh
if [ $(battery) -lt 100 ] && [ $(_battery-data 1 online) = "yes" ]; then
    notify "stupid kb combination"
    exit 1
fi

xdotool key XF86AudioPlay

# xdotool key --clearmodifiers XF86AudioPlay

# xdotool keyup KP_Space
# xdotool keyup Super_L
# xdotool key XF86AudioPlay

# xdotool key --clearmodifiers XF86AudioPlay
# sleep 0.1
# xdotool keyup KP_Space
# xdotool keyup Super_L
