#!/bin/sh
set -e

#mic-set-status off

amixer set Capture nocap > /dev/null
mic-status

volume 37

for sound in map close maximize minimize; do
    gsettings set org.cinnamon.sounds "$sound-enabled" true
done
