#!/bin/sh
set -e

#mic-set-status on

amixer set Capture cap > /dev/null
mic-status

volume 60

for sound in map close maximize minimize; do
    gsettings set org.cinnamon.sounds "$sound-enabled" false
done
