#!/bin/sh
while true; do
    for cmd in "$@"; do
echo "cmd[$cmd]"
echo "procx[$(procx "$cmd")]"
echo "ps[$(ps aux |grep -i "$cmd")]"
        if [ ! "$(procx "$cmd")" ]; then
echo "restarting.."
            # alert "process down; restarting: $cmd"
            # # eval "$cmd" &
            # $("$cmd") &
            # sh -c "$cmd" & # <-
            alert "process down: $cmd"
        fi
    done
    sleep 10
done
