#!/bin/sh
set -e

reg="@todo |// TODO: "
git --no-pager grep -I --extended-regexp --name-only "$reg"                \
    | xargs -n1 git --no-pager blame --show-name --show-number -w          \
    | grep "$(git config user.name)"                                       \
    | sed -r 's/^[^ ]+ +([^ ]+) +[0-9]+ \([^)]+ ([0-9]+)\)(.*)$/\1:\2 \3/' \
    | grep --extended-regexp --color=auto "$reg"
