#!/bin/sh
set -e
text="$1"
id="$2"

case "$(_os)" in
    linux)
        notify-send -- "$text"
        ;;
    mac)
        # fix: `open /opt/homebrew/opt/terminal-notifier/terminal-notifier.app`
        if [ "$text" ]; then
            if [ "$id" ]; then
                terminal-notifier -message "$text" -group "$id"
            else
                terminal-notifier -message "$text"
            fi
        else
            terminal-notifier -remove "$id"
        fi
        ;;
esac
