#!/bin/sh
set -e

program="$1"
path="$2"
prefix="$3"

if [ "$path" != "" ]; then
    if [ $(expr index "$path" /) = 0 ]; then
        filename="$path"
    else
        filename=$(expr "$path" : '.*/\([^/]*\)')
        dirLen=$(( $(expr length "$path") - $(expr length "$filename") - 1 ))
        cd "$(expr substr "$path" 1 "$dirLen")"
        # cd "`expr substr \"$path\" 1 \"$dirLen\"`"
    fi
fi

if [ "$prefix" != "" ]; then
    WINEPREFIX="$prefix" wine "$program" "$filename"
else
    wine "$program" "$filename"
fi
