#!/bin/sh
set -e

program="$1"
path="$2"
prefix="$3"

if [ "$path" != "" ]; then
    if ! echo "$path" |grep -Eq "^/"; then
        path="$(pwd)/$path"
    fi
    path="Z:$(echo "$path" |tr '/' "\\")"
fi

if [ "$prefix" != "" ]; then
    # to initialize:
    # - `WINEPREFIX=~/_/Programs/.wine2 regedit`
    # - set:
    #   My Computer
    #   > HKEY_CURRENT_USER
    #   > Control Panel
    #   > International
    #     edit:
    #     - sShortDate: yyyy-MM-dd
    #     - sTimeFormat: HH:mm:ss
    WINEPREFIX="$prefix" wine "$program" "$path"
else
    wine "$program" "$path"
fi
