#!/bin/sh
# "inxi -Sxxx"
for command in \
    "cat /etc/*release" \
    "cat /etc/*release/*" \
    "uname -a" \
    "lsb_release -d" \
    "hostnamectl" \
    "cat /proc/version" \
    "cat /etc/issue"\
; do
    echo "$command"
    eval "$command"
    hr
done
