#!/bin/sh
set -e

requirements="$(pwd)/requirements.txt"
if ! [ -f "$requirements" ]; then
    echo>&2 "requirements.txt not found"
    exit 1
fi

pip="$(python-venv)/pip"

outdated=""
for pkg_name in $($pip list --outdated |tail --lines=+3 |sed -r 's/^([^ ]+) .*$/\1/g'); do
    line="$(grep -E "^$pkg_name " "$requirements" ||:)"
    if [ "$line" ]; then
        outdated="$outdated $(echo "$line" |sed -r 's/^.*@(.+)@.*$/\1/')"
    else
        outdated="$outdated $pkg_name"
    fi
done
eval "$pip install --upgrade $outdated"
$pip freeze > "$requirements"
