#!/bin/sh
set -e

dir="$(pwd)"
requirements="$dir/requirements.txt"
if ! [ -f "$requirements" ]; then
    echo>&2 "requirements.txt not found"
    exit 1
fi
venv="$dir/.venv"
if ! [ -d "$venv" ]; then
    echo>&2 ".venv/ not found"
    exit 1
fi
bin="$(find "$venv" -maxdepth 1 -type d |sort --version-sort |tail -1)/bin"
if ! [ -d "$bin" ]; then
    echo>&2 "bin/ not found"
    exit 1
fi
export PATH="$bin:$PATH"
pip="pip"

outdated=""
for pkg_name in $($pip list --outdated |tail --lines=+3 |sed -r 's/^([^ ]+) .*$/\1/g'); do
    line="$(grep -E "^$pkg_name " "$requirements" ||:)"
    if [ "$line" ]; then
        outdated="$outdated $(echo "$line" |sed -r 's/^.*@(.+)@.*$/\1/')"
    else
        outdated="$outdated $pkg_name"
    fi
done
eval "$pip install --upgrade $outdated"
$pip freeze > "$requirements"
