#!/bin/sh
set -e

flags="-i"
flagX=""
flagP=""
flagQ=""
for input; do
    case $input in
        -x) flags="$flags -E"; flagX="1" ;; # exact command name
        -E) flags="$flags -E" ;;            # extended regexp
        -P) flagP="1" ;;                    # include caller and its parents
        -q) flagQ="1" ;;                    # do not warn about unsafe call
    esac
    search="$input"  # last one..
done

if [ ! "$flagX" ] && [ ! "$flagQ" ]; then
    if _is_in_script; then
        error="$(basename "$0") called from script without -x option"
        echo>&2 "$error"
        alert "$error"
    fi
fi

reg="$search"
if [ "$flagX" ]; then
    col="([^ ]+ +)"
    pid="$search"
    shell="(($(_shells)) +)"
    title="(/[^ ]+/)?$search"
    reg="^($col{10}$shell?$title( |$)|$col$pid )"
fi

procs="$(ps aux)"
if [ ! "$flagP" ]; then
    procs="$(echo "$procs" |grep -v -E "^[^ ]+ +($(_parents)) ")"  # except this `proc` and its parents
fi
echo "$procs" |grep $flags "$reg" |grep $flags --color=auto -- "$search" ||:
