#!/bin/sh
set -e

case "$(_os)" in
    linux)
        IDE "$HOME/_/Programs/vendor/JetBrains/Toolbox/pycharm-community/bin/pycharm.sh" "$@"
        ;;
    mac)
        IDE "$HOME/Library/Application Support/JetBrains/Toolbox/scripts/pycharm" "$@"
        ;;
esac
