#!/bin/sh
opts=""
if [ $# -ge 1 ]; then
    if [ "$1" = "-here" ] || [ "$1" = "-h" ]; then
        opts="-maxdepth 1"
    else
        opts="-iregex '.*$1.*'"
        if [ "$(_os)" = "linux" ]; then
            opts="-regextype awk $opts"
        fi
    fi
fi

random_file=$(eval "findp . $opts -type f" | shuf -n 1)

echo "$random_file"
gopen "$random_file"
