#!/bin/sh
set -e

reconnect=''
if [ "$1" = "--force" ]; then
    reconnect=1
else
    if ! connected7; then
        reconnect=1
    fi
fi
if [ "$reconnect" ]; then
    name="TP-LINK_7DA0"
    nmcli radio wifi off
    sleep 1s
    nmcli radio wifi on
    sleep 3s
    while ! nmcli --fields TYPE,STATE device status |grep -Eq '^wifi +connected *$'; do
        nmcli dev wifi list
        sleep 3
    done
fi
