#!/bin/sh
set -e
tag="$1"

last() { echo "$1" |sort --version-sort |tail --lines=1 ;}

tags="$(git tag --list)"
if [ "$tags" ]; then
    #last_tag="$(git describe --abbrev=0 --tags)"  # WTF
    last_tag="$(last "$tags")"

    if [ "$tag" = "help" ]; then
        echo "Options: $last_tag"
        exit 0
    fi

    if [ "$last_tag" = "$(last "$last_tag\n$tag")" ]; then
        echo>&2 "last tag: $last_tag"
        exit 1
    fi
fi

if ! echo "$tag" |grep -Eq "^v([0-9]+\.){2}[0-9]+$"; then
    echo>&2 "tag (vA.B.C) required"
    exit 1
fi

git tag --annotate "$tag" --message=""
git push origin "$tag"

#git push --delete origin v1.3.3
#git tag --delete v1.3.3
