#!/bin/sh
from=$(echo "$1" |sed -r 's / \\/ ')
to=$(echo "$2" |sed -r 's / \\/ ')
eval "find $(_path 3 "$@") \\( -type d -name .git -prune \\) -o -type f -print0" | xargs -0r -- sed -i -r "s/(^|[^0-9a-zA-Z])$from($|[^0-9a-zA-Z])/\1$to\2/g"
