#!/bin/sh
# no connection with parents

if [ "$1" = "-q" ]; then
    name=""
    cmd="$2"
else
    name="$1"
    cmd="$1"
fi

# eval "$cmd" &
# $("$cmd") &
# nohup

if [ "$name" ]; then
    sh -c "$cmd" >/dev/null 2>"$(errors for "$name")" &
else
    sh -c "$cmd" >/dev/null &
fi

echo "$!"
