#!/bin/sh
# no connection with parents

if [ $# -eq 1 ]; then
    name="$1"
    cmd="$1"
else
    name="$1"
    cmd="$2"
fi

if [ "$1" = "-q" ]; then
    name=""
else
    name="$(echo '$name'| sed -r 's/[^a-zA-Z0-9]/_/g')"
fi

# eval "$cmd" &
# $("$cmd") &
# nohup

if [ "$name" ]; then
    errors="$(errors for "$name")"
    sh -c "$cmd" >/dev/null 2>"$errors" &
else
    sh -c "$cmd" >/dev/null 2>&1 &
fi

echo "$!"
