#!/bin/bash
set -e

text="$1"
app="$2"
vol="$3"
if [ ! "$app" ]; then
    app=2
fi
if [ ! "$vol" ]; then
    vol=100
fi
play_file() {
    file="$HOME/.temp/$1/$text.wav"
    if ! [ -f "$file" ]; then
        eval "$(echo "$2" |sed -r "s~\[file]~'$file'~g")"
    fi

    # aplay "$file" 2> /dev/null
    # mplayer alsa:device=dmix "$file"
    cvlc --play-and-exit --gain $(calc -p $vol / 100) "$file" 2>/dev/null

    # rm "$file"
}
vol_unsupported() {
    if [ $vol -ne 100 ]; then
        echo "volume is not supported" >&2
    fi
}
case "$app" in
    1|espeak)
        vol_unsupported
        espeak -ven-us+f4 -s170 "$text"
        ;;
    2|pico2wave) play_file "pico2wave" "pico2wave -w=[file] '$text'" ;;
    3|festival)
        vol_unsupported
        festival -b '(voice_cmu_us_slt_arctic_hts)' '(SayText "'"$text"'")'
        ;;
    4|text2wave) play_file "text2wave" "text2wave -o [file] <(echo '$text')" ;;  # bash
    *)
        echo "Unknown app: $app" >&2
        exit 1
        ;;
esac
