#!/bin/sh

files="*"
dir="$(_path 1 "$@" |sed -r "s (^'|'\$)  g")"
files="$dir/$files"

pattern=".[!.]*"
if [ "$(echo $pattern)" != "$pattern" ]; then
    # files="$files $pattern"
    files="$files $dir/$pattern"
fi

pattern="..?*"
if [ "$(echo $pattern)" != "$pattern" ]; then
    # files="$files $pattern"
    files="$files $dir/$pattern"
fi

du -sch -- $files |sort -hr
# find . -maxdepth 1 -exec du -sh -- {} +
# find . -maxdepth 1 -execdir du -sh -- {} + |sort -hr
