#!/bin/bash
set -e
_highlander

url=127.0.0.1
port=8703

reg='^\[[^]]+\]  "[^G]*GET[^/]+/([^"]+[0-9a-zA-Z])[^"0-9a-zA-Z]*".*$'
# reg='^\[[^]]+\]  "[^G]*GET[^/]+/([[:print:]]+)[^[[:print:]]].*$'
# grep + sed don't work..
http-server -a $url -p $port -d false -i false 2>/dev/null |while read line; do
    if [ "$(echo "$line" |grep -E "$reg")" ]; then
        if [ "$(echo "$line" |grep -E 'Error \(404\): "Not found"$')" ]; then continue; fi

        uri="$(echo "$line" |sed -r "s~$reg~\1~")"
        # length=$(echo "$uri" |awk '{print length($0)}')
        # uri="$(echo "$uri" |cut -c1-$(($length-5)))"

        get_url_param (){ echo "$uri" |php -r "parse_str(substr(fgets(STDIN), 1), \$params); echo \$params['$1'];" ;}
        action=$(get_url_param "action")
        run_script (){
            cmd="$(dirname $0)/utils/system-server-scripts/$action.sh"
            for key in "$@"; do
                if [ "${key:0:1}" = "-" ]; then  # bash
                    cmd="$cmd $(get_url_param "${key:1}")"
                else
                    cmd="$cmd '$(get_url_param "$key")'"
                fi
            done
            run-detached "$cmd"
        }

        case "$action" in
            browser-key) run_script "title" "-key" ;;
            radio-nv)    run_script "title" ;;
            *)           echo>&2 "$0: unknown action: [$action]" ;;
        esac
    fi
done
