#!/bin/sh
list="$HOME/.temp/$(basename $0).txt"
case "$1" in
save) wmctrl -l |grep Vivaldi |sed -r 's/^0x\w+ +-?([0-9]+) +machine (.*)$/\1 \2/' > "$list" ;;
move)
    # cat "$list" |sed -r 's/'\''/'\''\\'\'''\''/' |sed -r 's/^([0-9]+) (.*)$/wmctrl -Fr '\''\2'\'' -t \1/' |awk '{system($0)}'
    cat "$list" |while read line; do
        # line=$(echo "$line" |sed -r 's/'\''/'\''\\'\'''\''/')
        pattern="^([0-9]+) (.*)\$"
        workspace=$(echo "$line" |sed -r "s/$pattern/\\1/")
        window=$(echo "$line" |sed -r "s/$pattern/\\2/")
        wmctrl -Fr "$window" -t $workspace
        wmctrl -Fr "$window" -b add,maximized_vert,maximized_horz
    done
    ;;
*) echo "options: save, move"
esac
