#!/bin/sh
file="$HOME/.temp/$(basename $0).txt"
pattern="^([^ ]+) ([0-9]+) (.*)\$"
case "$1" in
    list) wmctrl -l |grep Vivaldi |sed -r 's/^(0x\w+) +-?([0-9]+) +machine (.*)$/\1 \2 \3/' |sort ;;
    full)
        $0 list |while read line; do
            id=$(echo "$line" |sed -r "s/$pattern/\\1/")
            if ! [ "$(xprop -id "$id" |grep '_NET_WM_STATE(ATOM) = _NET_WM_STATE_MAXIMIZED_HORZ, _NET_WM_STATE_MAXIMIZED_VERT')" ]; then
                wmctrl -i -r "$id" -b add,maximized_vert,maximized_horz
            fi
        done
        ;;
    save) $0 list > "$file" ;;
    move)
        # cat "$file" |sed -r 's/'\''/'\''\\'\'''\''/g' |sed -r 's/^([0-9]+) (.*)$/wmctrl -F -r '\''\2'\'' -t \1/' |awk '{system($0)}'
        cat "$file" |while read line; do
            workspace=$(echo "$line" |sed -r "s/$pattern/\\2/")
            window=$(echo "$line" |sed -r "s/$pattern/\\3/")
            wmctrl -F -r "$window" -t $workspace
        done
        ;;
    listen)
        _highlander
        if [ ! "$($0 list)" ]; then
            i=0
            while [ $i -lt 30 ]; do
                t1=$($0 list |sed -r "s/$pattern/\\3/" |sort)
                t2=$(cat "$file" |sed -r "s/$pattern/\\3/" |sort)
                if [ "$t1" = "$t2" ]; then
                    sleep 3
                    break
                fi
                sleep 1
                i=$(calc -p -- "$i + 1")
            done
            $0 move
        fi

        sleep 1
        $0 full

        prev=0
        while true; do
            sleep 5
            if [ ! "$($0 list)" ]; then
                break
            fi
            if [ "$($0 list |wc -l)" -ge $prev ]; then
                $0 save
            fi
            prev="$($0 list |wc -l)"
        done
        ;;
    *) echo "options: list full save move listen"
esac
