#!/bin/sh
if [ $# -eq 1 ]; then
    pactl set-sink-volume alsa_output.pci-0000_00_1f.3.analog-stereo $1%
else
    pactl list sinks |grep -E '^.Volume:' |sed -r 's_^.*/ +([0-9]+)% +/ +-?[0-9,]+ dB$_\1_'
fi
