#!/bin/sh
set -e
window_name="$1"
timeout="$2"

[ "$timeout" ] || timeout=0

now (){ date +"%s" ;}
start="$(now)"
while :; do
#    reg='^ *pid = ([0-9]+) type="Foreground" .*$'
#    pid="$(lsappinfo list |grep -E --after-context=5 "^[0-9]+\) "'"'"$window_name"'"'"" |grep -E "$reg" |sed -r "s/$reg/\1/g")"
    reg="^([0-9]+) $window_name.*$"
    pid="$(_window-names |rg "$reg" |sed -r "s/$reg/\1/g")"

    if [ "$pid" ]; then
        break
    elif [ $(($(now) - start)) -gt "$timeout" ]; then
        alert "window \"$window_name\" is not open"
        exit 1
    else
        sleep 0.1
    fi
done

osascript -e '
    tell application "System Events"
        set targetPID to '"$pid"'
        repeat with proc in (every process whose unix id is targetPID)
            try
                set frontmost of proc to true
                return "Activated PID: " & targetPID
            end try
        end repeat
    end tell
' ||:

start="$(now)"
while :; do
    if _front-app |rg -q "^[0-9]+ $window_name"; then
        break
    elif [ $(($(now) - start)) -gt "$timeout" ]; then
        alert "Window \"$window_name\" was not activated"
        exit 1
    else
        sleep 0.1
    fi
done
