#!/bin/bash
set -e

sleep 10  # TODO: fix in `daemons`? Or remove. Is it actual?

connected(){ _external-display-connected && echo '1' || echo '' ;}
current="$(connected)"
while read line; do
    if echo "$line" |egrep --invert-match --quiet ' member=MonitorsChanged$'; then continue; fi
    new="$(connected)"
    if [ "$new" != "$current" ]; then
        if [ "$new" ]; then
            gsettings set org.cinnamon alttab-switcher-style 'icons+preview'
        else
            gsettings set org.cinnamon alttab-switcher-style 'coverflow'
        fi
        current="$new"
    fi
done < <(dbus-monitor "type='signal',path='/org/Cinnamon',interface='org.Cinnamon',member='MonitorsChanged'")
