#!/bin/bash
set -e

# log (){ echo "$(date-ft): $@" >> ~/.temp/git.log ;}
# log "$@"

nr_args=$#
if [ "${!nr_args}" = "--" ]; then
    nr_args=$(($nr_args-1))
fi
n=$nr_args
n1=$(($n - 1))
n2=$(($n - 2))
if [ $nr_args -ge 2 ]; then
    if [ "${!n1}" = "checkout" ]; then
        git-switch "${!n}"
        exit 0
    fi
fi
if [ $nr_args -ge 3 ]; then
    if [ "${!n2}" = "branch" ] && [ "${!n1}" = "-d" ]; then
        stash="$(gsh-list |grep -E "^stash@{[0-9]+}: On ${!n}: git-switch$" ||true)"
        if [ "$stash" ]; then
            stash="$(echo "$stash" |sed -r 's/^([^:]+):.+$/\1/')"
            git stash drop "$stash"
        fi
    fi
fi

# args=""
# for arg in "$@"; do args="$args $(printf "%q" "$arg")"; done
# eval "git $args"
_transfer git "$@"
