#!/bin/sh


_complete_full()
{
    if [ $SHELL = $(which bash) ]; then
        local PATH=$HOME/_/Programs/bin
        _command_offset 1
    fi
    if [ $SHELL = $(which zsh) ]; then
        COMPREPLY=( $(compgen -c) )
    fi
} &&
complete -F _complete_full copy fkill fuck parallel proc procx restart save-output whatsin  dt dtb rdt rdtb rdtbo tb


_complete_by_options() {
    cur="${COMP_WORDS[COMP_CWORD]}"
    command=""
    i=0
    while [ $i -lt $COMP_CWORD ]; do
        command="$command ${COMP_WORDS[$i]}"
        i=$(($i + 1))
    done
    list=$($command help |sed -r 's/Options: (.*)/\1/')
    COMPREPLY=( $(compgen -W "$list" -- ${cur}) )
}
complete -F _complete_by_options aqi brightness errors light location scene vivaldi-windows


_complete_files() {
    COMPREPLY=( $(ls -CF --group-directories-first) )
}
complete -F _complete_files gdf git-reset nr-files
