#!/bin/sh
_complete_vivaldi_windows() {
    cur="${COMP_WORDS[COMP_CWORD]}"
    list=$(vivaldi-windows help |sed -r 's/options: (.*)/\1/')
    COMPREPLY=( $(compgen -W "$list" -- ${cur}) )
}
complete -F _complete_vivaldi_windows vivaldi-windows
